### ISSUE TITLE
How do you load images with gatsby?

### ISSUE THREAD

**Issue by urimaxi** [Hyperobjekt/repeat-site#13]

**Comment by Lane** [comment]
hey @urimaxi, there are a few different ways.

## Using `gatsby-plugin-image` to automatically optimize and size images for different devices

the easiest way to use an image is with the [`<StaticImage />` component from gatsby-plugin-image](https://www.gatsbyjs.com/plugins/gatsby-plugin-image/#static-images).  the usage is similar to a standard `<img />` tag and lets you specify some props for optimizing the image.

if you need a dynamic image that is queried based on some graphql params, check out the [dynamic image documentation](https://www.gatsbyjs.com/plugins/gatsby-plugin-image/#dynamic-images)


## Using images as-is

if you don't need any image optimization, you can put images somewhere in the `/static/` folder at the root of the repo and it will get copied to the root directory of the site.

e.g. image file in `/static/images/sample.jpg`

`<img src="/images/sample.jpg" alt="image, no optimization" />`

**Comment by urimaxi** [comment]
Awesome! Thanks - used `gatsby-plugin-image`
