### ISSUE TITLE
Add style for hyperlinked text

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/repeat-site#64]
## Objective
Add style for hyperlinks within descriptive text

From Jesse: 
> I also noticed that links on the page are not differentiated visually from the other text. For exmaple "Net-Zero America" here is a link but looks same as rest of text

![image (3).png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/653f2e32-1962-497d-b8b9-eeb1fb5c002e)

**Comment by ekmason** [comment]
## Internal QA Review
- [ ] Add an underline that matches text color for hyperlinked text within the body (see Jonathan's example in the first paragraph of the [policy page mockups](https://www.figma.com/file/e3BrG5TGLUzOdr3I84bUmG/REPEAT?node-id=247%3A1333)

**Comment by james-minton** [comment]
### Internal QA Review - 2nd pass

- [ ] Seeing this style implemented in certain places but not others on the deployed site, e.g. About page, first paragraph: "Net-Zero Study Team" is a link and should have styling. 

![Screen Shot 2021-07-23 at 10 25 51 AM](https://user-images.githubusercontent.com/33635008/126796704-6ae85288-a429-4048-aacf-228ee20869a3.png)
